// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "token": string;
      "userId": string;
      "collectionName": string;
      "includeTranscript": boolean;
      "autoSyncIntervalMin": number;
      "serverUrl": string;
      "lastSyncTime": string;
    };
  }
}
